-- Comentario Linear
/*
	Comentarios
		Em
			Bloco
*/

--Criar um banco de dados
CREATE DATABASE BDCONTATOS;

GO --EXECUTA TODOS OS COMANDOS ANTERIORES ANTES DE CONTINUAR

--Selecionar a base de dados criada
USE BDCONTATOS;

--DROP TABLE TBAmigos

CREATE TABLE TBAmigos(
	ID		INT IDENTITY PRIMARY KEY,
	NOME	VARCHAR(50) NOT NULL,
	TEL		CHAR(11) NOT NULL UNIQUE
);

--ALTER TABLE TBAmigos ADD CONSTRAINT PKTBAmigos PRIMARY KEY (ID);

CREATE TABLE TBUsuarios(
	USUARIO	VARCHAR(30) PRIMARY KEY,
	SENHA	CHAR(32) NOT NULL, -- MD5 -->32 / SHA1 -->40
	TIPO_USUARIO CHAR(1) DEFAULT 'U' NOT NULL,
	CONSTRAINT CK_TBUsuario CHECK ( (TIPO_USUARIO = 'U') OR (TIPO_USUARIO='A') )
);

INSERT INTO TBUsuarios(USUARIO,SENHA,TIPO_USUARIO)
	VALUES('ANDERSON','123456','A');

INSERT INTO TBUsuarios(USUARIO,SENHA,TIPO_USUARIO)
	VALUES('PAULO','654321','U');

INSERT INTO TBUsuarios(USUARIO,SENHA)
	VALUES('RODRIGO','123ABC');

SELECT * FROM TBUsuarios

INSERT INTO TBAmigos(NOME,TEL)
VALUES(''); DROP DATABASE BDCONTATOS;--','11988887777')





DECLARE @teste varchar(10);
set @teste = 'insert into ';
INSERT INTO TBAmigos(NOME,TEL) values(@teste,'123123');



INSERT INTO TBAmigos(NOME,TEL) VALUES ('JOAO','1111');
INSERT INTO TBAmigos(NOME,TEL) VALUES ('PEDRO','2222');
INSERT INTO TBAmigos(NOME,TEL) VALUES ('JOSE','3333');
SELECT * FROM TBAmigos

BEGIN TRANSACTION COMANDOS;
UPDATE TBAmigos SET NOME = 'ABACAXI';

ROLLBACK;

COMMIT;

--truncate table tbamigos

SELECT top 3 ID,NOME,TEL FROM TBAmigos
order by NOME 
--WHERE NOME LIKE '%F%';

SELECT ID,NOME,TEL FROM TBAmigos
where ID = 79

delete from TBAmigos